insert into "country"("id", "name") values ('AF', 'Afghanistan');
insert into "country"("id", "name") values ('AX', 'Åland Islands');
insert into "country"("id", "name") values ('AL', 'Albania');
insert into "country"("id", "name") values ('DZ', 'Algeria');
insert into "country"("id", "name") values ('AS', 'American Samoa');
insert into "country"("id", "name") values ('AD', 'Andorra');
insert into "country"("id", "name") values ('AO', 'Angola');
insert into "country"("id", "name") values ('AI', 'Anguilla');
insert into "country"("id", "name") values ('AQ', 'Antarctica');
insert into "country"("id", "name") values ('AG', 'Antigua & Barbuda');
insert into "country"("id", "name") values ('AR', 'Argentina');
insert into "country"("id", "name") values ('AM', 'Armenia');
insert into "country"("id", "name") values ('AW', 'Aruba');
insert into "country"("id", "name") values ('AC', 'Ascension Island');
insert into "country"("id", "name") values ('AU', 'Australia');
insert into "country"("id", "name") values ('AT', 'Austria');
insert into "country"("id", "name") values ('AZ', 'Azerbaijan');
insert into "country"("id", "name") values ('BS', 'Bahamas');
insert into "country"("id", "name") values ('BH', 'Bahrain');
insert into "country"("id", "name") values ('BD', 'Bangladesh');
insert into "country"("id", "name") values ('BB', 'Barbados');
insert into "country"("id", "name") values ('BY', 'Belarus');
insert into "country"("id", "name") values ('BE', 'Belgium');
insert into "country"("id", "name") values ('BZ', 'Belize');
insert into "country"("id", "name") values ('BJ', 'Benin');
insert into "country"("id", "name") values ('BM', 'Bermuda');
insert into "country"("id", "name") values ('BT', 'Bhutan');
insert into "country"("id", "name") values ('BO', 'Bolivia');
insert into "country"("id", "name") values ('BA', 'Bosnia & Herzegovina');
insert into "country"("id", "name") values ('BW', 'Botswana');
insert into "country"("id", "name") values ('BR', 'Brazil');
insert into "country"("id", "name") values ('IO', 'British Indian Ocean Territory');
insert into "country"("id", "name") values ('VG', 'British Virgin Islands');
insert into "country"("id", "name") values ('BN', 'Brunei');
insert into "country"("id", "name") values ('BG', 'Bulgaria');
insert into "country"("id", "name") values ('BF', 'Burkina Faso');
insert into "country"("id", "name") values ('BI', 'Burundi');
insert into "country"("id", "name") values ('KH', 'Cambodia');
insert into "country"("id", "name") values ('CM', 'Cameroon');
insert into "country"("id", "name") values ('CA', 'Canada');
insert into "country"("id", "name") values ('IC', 'Canary Islands');
insert into "country"("id", "name") values ('CV', 'Cape Verde');
insert into "country"("id", "name") values ('BQ', 'Caribbean Netherlands');
insert into "country"("id", "name") values ('KY', 'Cayman Islands');
insert into "country"("id", "name") values ('CF', 'Central African Republic');
insert into "country"("id", "name") values ('EA', 'Ceuta & Melilla');
insert into "country"("id", "name") values ('TD', 'Chad');
insert into "country"("id", "name") values ('CL', 'Chile');
insert into "country"("id", "name") values ('CN', 'China');
insert into "country"("id", "name") values ('CX', 'Christmas Island');
insert into "country"("id", "name") values ('CC', 'Cocos (Keeling) Islands');
insert into "country"("id", "name") values ('CO', 'Colombia');
insert into "country"("id", "name") values ('KM', 'Comoros');
insert into "country"("id", "name") values ('CG', 'Congo - Brazzaville');
insert into "country"("id", "name") values ('CD', 'Congo - Kinshasa');
insert into "country"("id", "name") values ('CK', 'Cook Islands');
insert into "country"("id", "name") values ('CR', 'Costa Rica');
insert into "country"("id", "name") values ('CI', 'Côte d’Ivoire');
insert into "country"("id", "name") values ('HR', 'Croatia');
insert into "country"("id", "name") values ('CU', 'Cuba');
insert into "country"("id", "name") values ('CW', 'Curaçao');
insert into "country"("id", "name") values ('CY', 'Cyprus');
insert into "country"("id", "name") values ('CZ', 'Czechia');
insert into "country"("id", "name") values ('DK', 'Denmark');
insert into "country"("id", "name") values ('DG', 'Diego Garcia');
insert into "country"("id", "name") values ('DJ', 'Djibouti');
insert into "country"("id", "name") values ('DM', 'Dominica');
insert into "country"("id", "name") values ('DO', 'Dominican Republic');
insert into "country"("id", "name") values ('EC', 'Ecuador');
insert into "country"("id", "name") values ('EG', 'Egypt');
insert into "country"("id", "name") values ('SV', 'El Salvador');
insert into "country"("id", "name") values ('GQ', 'Equatorial Guinea');
insert into "country"("id", "name") values ('ER', 'Eritrea');
insert into "country"("id", "name") values ('EE', 'Estonia');
insert into "country"("id", "name") values ('ET', 'Ethiopia');
insert into "country"("id", "name") values ('EZ', 'Eurozone');
insert into "country"("id", "name") values ('FK', 'Falkland Islands');
insert into "country"("id", "name") values ('FO', 'Faroe Islands');
insert into "country"("id", "name") values ('FJ', 'Fiji');
insert into "country"("id", "name") values ('FI', 'Finland');
insert into "country"("id", "name") values ('FR', 'France');
insert into "country"("id", "name") values ('GF', 'French Guiana');
insert into "country"("id", "name") values ('PF', 'French Polynesia');
insert into "country"("id", "name") values ('TF', 'French Southern Territories');
insert into "country"("id", "name") values ('GA', 'Gabon');
insert into "country"("id", "name") values ('GM', 'Gambia');
insert into "country"("id", "name") values ('GE', 'Georgia');
insert into "country"("id", "name") values ('DE', 'Germany');
insert into "country"("id", "name") values ('GH', 'Ghana');
insert into "country"("id", "name") values ('GI', 'Gibraltar');
insert into "country"("id", "name") values ('GR', 'Greece');
insert into "country"("id", "name") values ('GL', 'Greenland');
insert into "country"("id", "name") values ('GD', 'Grenada');
insert into "country"("id", "name") values ('GP', 'Guadeloupe');
insert into "country"("id", "name") values ('GU', 'Guam');
insert into "country"("id", "name") values ('GT', 'Guatemala');
insert into "country"("id", "name") values ('GG', 'Guernsey');
insert into "country"("id", "name") values ('GN', 'Guinea');
insert into "country"("id", "name") values ('GW', 'Guinea-Bissau');
insert into "country"("id", "name") values ('GY', 'Guyana');
insert into "country"("id", "name") values ('HT', 'Haiti');
insert into "country"("id", "name") values ('HN', 'Honduras');
insert into "country"("id", "name") values ('HK', 'Hong Kong SAR China');
insert into "country"("id", "name") values ('HU', 'Hungary');
insert into "country"("id", "name") values ('IS', 'Iceland');
insert into "country"("id", "name") values ('IN', 'India');
insert into "country"("id", "name") values ('ID', 'Indonesia');
insert into "country"("id", "name") values ('IR', 'Iran');
insert into "country"("id", "name") values ('IQ', 'Iraq');
insert into "country"("id", "name") values ('IE', 'Ireland');
insert into "country"("id", "name") values ('IM', 'Isle of Man');
insert into "country"("id", "name") values ('IL', 'Israel');
insert into "country"("id", "name") values ('IT', 'Italy');
insert into "country"("id", "name") values ('JM', 'Jamaica');
insert into "country"("id", "name") values ('JP', 'Japan');
insert into "country"("id", "name") values ('JE', 'Jersey');
insert into "country"("id", "name") values ('JO', 'Jordan');
insert into "country"("id", "name") values ('KZ', 'Kazakhstan');
insert into "country"("id", "name") values ('KE', 'Kenya');
insert into "country"("id", "name") values ('KI', 'Kiribati');
insert into "country"("id", "name") values ('XK', 'Kosovo');
insert into "country"("id", "name") values ('KW', 'Kuwait');
insert into "country"("id", "name") values ('KG', 'Kyrgyzstan');
insert into "country"("id", "name") values ('LA', 'Laos');
insert into "country"("id", "name") values ('LV', 'Latvia');
insert into "country"("id", "name") values ('LB', 'Lebanon');
insert into "country"("id", "name") values ('LS', 'Lesotho');
insert into "country"("id", "name") values ('LR', 'Liberia');
insert into "country"("id", "name") values ('LY', 'Libya');
insert into "country"("id", "name") values ('LI', 'Liechtenstein');
insert into "country"("id", "name") values ('LT', 'Lithuania');
insert into "country"("id", "name") values ('LU', 'Luxembourg');
insert into "country"("id", "name") values ('MO', 'Macau SAR China');
insert into "country"("id", "name") values ('MK', 'Macedonia');
insert into "country"("id", "name") values ('MG', 'Madagascar');
insert into "country"("id", "name") values ('MW', 'Malawi');
insert into "country"("id", "name") values ('MY', 'Malaysia');
insert into "country"("id", "name") values ('MV', 'Maldives');
insert into "country"("id", "name") values ('ML', 'Mali');
insert into "country"("id", "name") values ('MT', 'Malta');
insert into "country"("id", "name") values ('MH', 'Marshall Islands');
insert into "country"("id", "name") values ('MQ', 'Martinique');
insert into "country"("id", "name") values ('MR', 'Mauritania');
insert into "country"("id", "name") values ('MU', 'Mauritius');
insert into "country"("id", "name") values ('YT', 'Mayotte');
insert into "country"("id", "name") values ('MX', 'Mexico');
insert into "country"("id", "name") values ('FM', 'Micronesia');
insert into "country"("id", "name") values ('MD', 'Moldova');
insert into "country"("id", "name") values ('MC', 'Monaco');
insert into "country"("id", "name") values ('MN', 'Mongolia');
insert into "country"("id", "name") values ('ME', 'Montenegro');
insert into "country"("id", "name") values ('MS', 'Montserrat');
insert into "country"("id", "name") values ('MA', 'Morocco');
insert into "country"("id", "name") values ('MZ', 'Mozambique');
insert into "country"("id", "name") values ('MM', 'Myanmar (Burma)');
insert into "country"("id", "name") values ('NA', 'Namibia');
insert into "country"("id", "name") values ('NR', 'Nauru');
insert into "country"("id", "name") values ('NP', 'Nepal');
insert into "country"("id", "name") values ('NL', 'Netherlands');
insert into "country"("id", "name") values ('NC', 'New Caledonia');
insert into "country"("id", "name") values ('NZ', 'New Zealand');
insert into "country"("id", "name") values ('NI', 'Nicaragua');
insert into "country"("id", "name") values ('NE', 'Niger');
insert into "country"("id", "name") values ('NG', 'Nigeria');
insert into "country"("id", "name") values ('NU', 'Niue');
insert into "country"("id", "name") values ('NF', 'Norfolk Island');
insert into "country"("id", "name") values ('KP', 'North Korea');
insert into "country"("id", "name") values ('MP', 'Northern Mariana Islands');
insert into "country"("id", "name") values ('NO', 'Norway');
insert into "country"("id", "name") values ('OM', 'Oman');
insert into "country"("id", "name") values ('PK', 'Pakistan');
insert into "country"("id", "name") values ('PW', 'Palau');
insert into "country"("id", "name") values ('PS', 'Palestinian Territories');
insert into "country"("id", "name") values ('PA', 'Panama');
insert into "country"("id", "name") values ('PG', 'Papua New Guinea');
insert into "country"("id", "name") values ('PY', 'Paraguay');
insert into "country"("id", "name") values ('PE', 'Peru');
insert into "country"("id", "name") values ('PH', 'Philippines');
insert into "country"("id", "name") values ('PN', 'Pitcairn Islands');
insert into "country"("id", "name") values ('PL', 'Poland');
insert into "country"("id", "name") values ('PT', 'Portugal');
insert into "country"("id", "name") values ('PR', 'Puerto Rico');
insert into "country"("id", "name") values ('QA', 'Qatar');
insert into "country"("id", "name") values ('RE', 'Réunion');
insert into "country"("id", "name") values ('RO', 'Romania');
insert into "country"("id", "name") values ('RU', 'Russia');
insert into "country"("id", "name") values ('RW', 'Rwanda');
insert into "country"("id", "name") values ('WS', 'Samoa');
insert into "country"("id", "name") values ('SM', 'San Marino');
insert into "country"("id", "name") values ('ST', 'São Tomé & Príncipe');
insert into "country"("id", "name") values ('SA', 'Saudi Arabia');
insert into "country"("id", "name") values ('SN', 'Senegal');
insert into "country"("id", "name") values ('RS', 'Serbia');
insert into "country"("id", "name") values ('SC', 'Seychelles');
insert into "country"("id", "name") values ('SL', 'Sierra Leone');
insert into "country"("id", "name") values ('SG', 'Singapore');
insert into "country"("id", "name") values ('SX', 'Sint Maarten');
insert into "country"("id", "name") values ('SK', 'Slovakia');
insert into "country"("id", "name") values ('SI', 'Slovenia');
insert into "country"("id", "name") values ('SB', 'Solomon Islands');
insert into "country"("id", "name") values ('SO', 'Somalia');
insert into "country"("id", "name") values ('ZA', 'South Africa');
insert into "country"("id", "name") values ('GS', 'South Georgia & South Sandwich Islands');
insert into "country"("id", "name") values ('KR', 'South Korea');
insert into "country"("id", "name") values ('SS', 'South Sudan');
insert into "country"("id", "name") values ('ES', 'Spain');
insert into "country"("id", "name") values ('LK', 'Sri Lanka');
insert into "country"("id", "name") values ('BL', 'St. Barthélemy');
insert into "country"("id", "name") values ('SH', 'St. Helena');
insert into "country"("id", "name") values ('KN', 'St. Kitts & Nevis');
insert into "country"("id", "name") values ('LC', 'St. Lucia');
insert into "country"("id", "name") values ('MF', 'St. Martin');
insert into "country"("id", "name") values ('PM', 'St. Pierre & Miquelon');
insert into "country"("id", "name") values ('VC', 'St. Vincent & Grenadines');
insert into "country"("id", "name") values ('SD', 'Sudan');
insert into "country"("id", "name") values ('SR', 'Suriname');
insert into "country"("id", "name") values ('SJ', 'Svalbard & Jan Mayen');
insert into "country"("id", "name") values ('SZ', 'Swaziland');
insert into "country"("id", "name") values ('SE', 'Sweden');
insert into "country"("id", "name") values ('CH', 'Switzerland');
insert into "country"("id", "name") values ('SY', 'Syria');
insert into "country"("id", "name") values ('TW', 'Taiwan');
insert into "country"("id", "name") values ('TJ', 'Tajikistan');
insert into "country"("id", "name") values ('TZ', 'Tanzania');
insert into "country"("id", "name") values ('TH', 'Thailand');
insert into "country"("id", "name") values ('TL', 'Timor-Leste');
insert into "country"("id", "name") values ('TG', 'Togo');
insert into "country"("id", "name") values ('TK', 'Tokelau');
insert into "country"("id", "name") values ('TO', 'Tonga');
insert into "country"("id", "name") values ('TT', 'Trinidad & Tobago');
insert into "country"("id", "name") values ('TA', 'Tristan da Cunha');
insert into "country"("id", "name") values ('TN', 'Tunisia');
insert into "country"("id", "name") values ('TR', 'Turkey');
insert into "country"("id", "name") values ('TM', 'Turkmenistan');
insert into "country"("id", "name") values ('TC', 'Turks & Caicos Islands');
insert into "country"("id", "name") values ('TV', 'Tuvalu');
insert into "country"("id", "name") values ('UM', 'U.S. Outlying Islands');
insert into "country"("id", "name") values ('VI', 'U.S. Virgin Islands');
insert into "country"("id", "name") values ('UG', 'Uganda');
insert into "country"("id", "name") values ('UA', 'Ukraine');
insert into "country"("id", "name") values ('AE', 'United Arab Emirates');
insert into "country"("id", "name") values ('GB', 'United Kingdom');
insert into "country"("id", "name") values ('UN', 'United Nations');
insert into "country"("id", "name") values ('US', 'United States');
insert into "country"("id", "name") values ('UY', 'Uruguay');
insert into "country"("id", "name") values ('UZ', 'Uzbekistan');
insert into "country"("id", "name") values ('VU', 'Vanuatu');
insert into "country"("id", "name") values ('VA', 'Vatican City');
insert into "country"("id", "name") values ('VE', 'Venezuela');
insert into "country"("id", "name") values ('VN', 'Vietnam');
insert into "country"("id", "name") values ('WF', 'Wallis & Futuna');
insert into "country"("id", "name") values ('EH', 'Western Sahara');
insert into "country"("id", "name") values ('YE', 'Yemen');
insert into "country"("id", "name") values ('ZM', 'Zambia');
insert into "country"("id", "name") values ('ZW', 'Zimbabwe');
